### ISSUE TITLE
Не работает Elasticsearch

### ISSUE THREAD

**Issue by filippovano** [ensi-platform/elc-workspace#27]
Делаю `elc start elastic` контейнер запускается, но сам эластик не работает.  
Вываливает ошибку `No alive nodes found in your cluster`

Пофиксил выставив в services/elastic/elastic.yml в environment опцию "xpack.security.enabled=false"

**Comment by MadridianFox** [comment]
Прошло уже слишком много времени чтобы искать концы.
Проблема скорее всего уже давно решена.
