### ISSUE TITLE
Starting Error response from daemon: cannot join network of a non running container

### ISSUE THREAD

**Issue by eljump** [ensi-platform/elc-workspace#8]
Разворачиваю по инструкции.
Сервис Admin Auth.
Выполнение команды : `elc npm install`
Закончилось ошибкой:
`
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 1/2
 ⠿ Container ensi-units-admin-auth-app-1    Started                                                                                                                                                                            
 ⠿ Container ensi-units-admin-auth-nginx-1  Starting                                                                                                                                                                     
Error response from daemon: cannot join network of a non running container: ce2f2c762a97bbb19c02697205f543139bf3898292fd0006c837053e08ad1a00
exit status 1
`
Сервис nginx не стартует, показывая эту же ошибку

**Comment by MadridianFox** [comment]
Это дубль проблемы #7
